
# build PRs to master and git tags
# https://github.com/travis-ci/travis-ci/issues/1147#issuecomment-160820262
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

language: generic

jobs:
  include:
    - stage: tests
      name: Java tests
      script:
        - lein do clean, compile, check, eastwood, test

    - stage: tests
      name: JavaScript tests
      script:
        # lein -m cljs.main --help
        - lein run -m cljs.main -t node -m carocad.frechet.test-runner

    - stage: Release
      if: tag IS present
      script:
        - lein compile
      deploy:
        - provider: script
          script: lein deploy clojars
          skip_cleanup: true
          on:
            tags: true
